# Site settings
title: Dan Lu
email: daniel.bin.lu [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Design Technologist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://holistudio.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
